# Generated by Django 6.0 on 2025-12-23 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_company_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Headquarters address of the company', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Official email address of the company', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=' ', help_text='Contact phone number for the company', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Official website of the company', verbose_name='Website'),
        ),
    ]
