# Generated by Django 6.0 on 2025-12-23 13:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options_company_created_by_and_more'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Professional email address', max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(help_text='Format: +1234567890', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('designation', models.CharField(help_text='Position/Title in the company', max_length=255, verbose_name='Designation')),
                ('status', models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('HIRED', 'Hired'), ('NOT_ACCEPTED', 'Not Accepted')], default='APPLICATION_RECEIVED', max_length=50, verbose_name='Employee Status')),
                ('hired_on', models.DateField(blank=True, help_text='Date when employee was hired', null=True, verbose_name='Hired On')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_employed', models.PositiveIntegerField(default=0, help_text='Automatically calculated from hire date', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Days Employed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='Company')),
                ('department', models.ForeignKey(blank=True, limit_choices_to={'company': models.F('company')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department', verbose_name='Department')),
                ('user_account', models.OneToOneField(blank=True, help_text='Linked user account for system access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='employees_e_last_na_99a4c0_idx'), models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'), models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'), models.Index(fields=['hired_on'], name='employees_e_hired_o_c9c124_idx'), models.Index(fields=['company', 'department'], name='employees_e_company_ba5a2a_idx')],
            },
        ),
    ]
