# Generated by Django 6.0 on 2025-12-23 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_options_department_created_by_and_more'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_last_na_99a4c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_email_8f5bbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_status_61c2f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_hired_o_c9c124_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_company_ba5a2a_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(blank=True, help_text='Date when employee was hired', null=True, verbose_name='Hired Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(help_text='Position/Title in the company', max_length=100, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Professional email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(help_text='Format: +1234567890', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10,}$', 'Mobile number must be at least 10 digits')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired'), ('not_accepted', 'Not Accepted')], default='application_received', max_length=20, verbose_name='Employee Status'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='days_employed',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hired_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_account',
        ),
    ]
